---
abstract: 'Signal masks made easy'
author:
  - 'Leon Timmermans <fawaka@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Signal-Mask
requires:
  Carp: 0
  Config: 0
  Const::Fast: 0
  IPC::Signal: 0
  POSIX: 0
  Thread::SigMask: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Signal-Mask
  repository: git://github.com/Leont/signal-mask.git
version: 0.006
