---
name: Signal-Mask
version: 0.002
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Signal masks made easy
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Module::Build: 0.28
  Test::More: 0
requires:
  Const::Fast: 0
  IPC::Signal: 0
  Thread::SigMask: 0.002
  perl: 5.006
configure_requires:
  Module::Build: 0.28
provides:
  Signal::Mask:
    file: lib/Signal/Mask.pm
    version: 0.002
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
